name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    # - run: npm run lint         # Lint the code, omitted to later steps
    - run: npm run build --if-present
    # Docker packaging steps
    - name: Build Docker Image
      run: |
        docker build -t mohamedjarboua/red-tetris-back:${{ github.sha }} .
      
    #- name: Log in to Docker Hub
     # uses: docker/login-action@v3
      #with:
       # username: ${{ secrets.DOCKER_USERNAME }}
        #password: ${{ secrets.DOCKER_PASSWORD }}

    #- name: Push Docker Image
     # run: |
      #  docker push mohamedjarboua/red-tetris-back:${{ github.sha }}
